/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef match_CONSTANTS_H
#define match_CONSTANTS_H

#include "match_types.h"

namespace match_service {

class matchConstants {
 public:
  matchConstants();

};

extern const matchConstants g_match_constants;

} // namespace

#endif
