/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "match_constants.h"

namespace match_service {

const matchConstants g_match_constants;

matchConstants::matchConstants() {
}

} // namespace

